# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b980898452b07aab4c30e7f643a97431"
name = "boilerplate"
handle = "boilerplate-18"
application_url = "https://downtown-university-enter-probability.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "creators-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://downtown-university-enter-probability.trycloudflare.com/auth/callback",
  "https://downtown-university-enter-probability.trycloudflare.com/auth/shopify/callback",
  "https://downtown-university-enter-probability.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
